### ISSUE TITLE
pagina 59

### ISSUE THREAD

**Issue by danilodimoia** [alessandrocucci/ml-book#1]
Ciao, la matrice X a pagina 60 non è stata creata, confonde un po' le idee. Quella nella pagina precedente inizia da 1 e arriva a 9.
Inoltre a pagina 59, riga 23, X.reshape(3,3) non modifica la matrice X. Bisogna fare X = X.reshape(3,3)

**Comment by alessandrocucci** [comment]
Grazie per la precisazione. Mi era sfuggita!
